package com.protocols
{
   import com.Data;
   
   public class Mod_Item
   {
       
      
      public function Mod_Item()
      {
         super();
      }
      
      public static function register(param1:Data) : void
      {
         param1.registerDataCallback(Mod_Item_Base.avatar_card_off,param1.item.avatar_card_off);
         param1.registerDataCallback(Mod_Item_Base.classify_pack,param1.item.classify_pack);
         param1.registerDataCallback(Mod_Item_Base.classify_warehouse,param1.item.classify_warehouse);
         param1.registerDataCallback(Mod_Item_Base.classify_home_warehouse,param1.item.classify_home_warehouse);
         param1.registerDataCallback(Mod_Item_Base.add_pack_grid,param1.item.add_pack_grid);
         param1.registerDataCallback(Mod_Item_Base.add_warehouse_grid,param1.item.add_warehouse_grid);
         param1.registerDataCallback(Mod_Item_Base.get_empty_grid_number,param1.item.get_empty_grid_number);
         param1.registerDataCallback(Mod_Item_Base.get_item_basical_infos,param1.item.get_item_basical_infos);
         param1.registerDataCallback(Mod_Item_Base.get_player_warehouse_grids,param1.item.get_player_warehouse_grids);
         param1.registerDataCallback(Mod_Item_Base.get_player_home_warehouse_grids,param1.item.get_player_home_warehouse_grids);
         param1.registerDataCallback(Mod_Item_Base.get_player_pack_item_list,param1.item.get_player_pack_item_list);
         param1.registerDataCallback(Mod_Item_Base.get_role_equip_list,param1.item.get_role_equip_list);
         param1.registerDataCallback(Mod_Item_Base.get_npc_item_list,param1.item.get_npc_item_list);
         param1.registerDataCallback(Mod_Item_Base.get_npc_recycle_item_list,param1.item.get_npc_recycle_item_list);
         param1.registerDataCallback(Mod_Item_Base.get_player_role_equip_list,param1.item.get_player_role_equip_list);
         param1.registerDataCallback(Mod_Item_Base.get_yupai_npc_item_list,param1.item.get_yupai_npc_item_list);
         param1.registerDataCallback(Mod_Item_Base.player_buy_yupai_npc_item,param1.item.player_buy_yupai_npc_item);
         param1.registerDataCallback(Mod_Item_Base.change_pack_item_grid,param1.item.change_pack_item_grid);
         param1.registerDataCallback(Mod_Item_Base.change_warehouse_item_grid,param1.item.change_warehouse_item_grid);
         param1.registerDataCallback(Mod_Item_Base.change_home_warehouse_item_grid,param1.item.change_home_warehouse_item_grid);
         param1.registerDataCallback(Mod_Item_Base.move_pack_grid_item_to_warehouse,param1.item.move_pack_grid_item_to_warehouse);
         param1.registerDataCallback(Mod_Item_Base.move_pack_grid_item_to_home_warehouse,param1.item.move_pack_grid_item_to_home_warehouse);
         param1.registerDataCallback(Mod_Item_Base.move_warehouse_grid_item_to_pack,param1.item.move_warehouse_grid_item_to_pack);
         param1.registerDataCallback(Mod_Item_Base.move_home_warehouse_grid_item_to_pack,param1.item.move_home_warehouse_grid_item_to_pack);
         param1.registerDataCallback(Mod_Item_Base.drop_pack_grid_item,param1.item.drop_pack_grid_item);
         param1.registerDataCallback(Mod_Item_Base.drop_warehouse_grid_item,param1.item.drop_warehouse_grid_item);
         param1.registerDataCallback(Mod_Item_Base.drop_home_warehouse_grid_item,param1.item.drop_home_warehouse_grid_item);
         param1.registerDataCallback(Mod_Item_Base.remove_player_role_equipment,param1.item.remove_player_role_equipment);
         param1.registerDataCallback(Mod_Item_Base.equip_player_role_item,param1.item.equip_player_role_item);
         param1.registerDataCallback(Mod_Item_Base.player_buy_npc_item,param1.item.player_buy_npc_item);
         param1.registerDataCallback(Mod_Item_Base.player_sell_item,param1.item.player_sell_item);
         param1.registerDataCallback(Mod_Item_Base.player_buy_back_item,param1.item.player_buy_back_item);
         param1.registerDataCallback(Mod_Item_Base.player_use_grid_item,param1.item.player_use_grid_item);
         param1.registerDataCallback(Mod_Item_Base.player_use_grid_reel,param1.item.player_use_grid_reel);
         param1.registerDataCallback(Mod_Item_Base.player_use_grid_elixir,param1.item.player_use_grid_elixir);
         param1.registerDataCallback(Mod_Item_Base.get_facture_reel_data,param1.item.get_facture_reel_data);
         param1.registerDataCallback(Mod_Item_Base.get_player_role_elixir_data,param1.item.get_player_role_elixir_data);
         param1.registerDataCallback(Mod_Item_Base.has_level_gift_item,param1.item.has_level_gift_item);
         param1.registerDataCallback(Mod_Item_Base.player_get_super_gift,param1.item.player_get_super_gift);
         param1.registerDataCallback(Mod_Item_Base.get_player_role_elixir_record,param1.item.get_player_role_elixir_record);
         param1.registerDataCallback(Mod_Item_Base.player_use_ingot_elixir,param1.item.player_use_ingot_elixir);
         param1.registerDataCallback(Mod_Item_Base.player_reel_need_item,param1.item.player_reel_need_item);
         param1.registerDataCallback(Mod_Item_Base.player_equip_use_reel,param1.item.player_equip_use_reel);
         param1.registerDataCallback(Mod_Item_Base.get_player_item_facture_reel_data,param1.item.get_player_item_facture_reel_data);
         param1.registerDataCallback(Mod_Item_Base.notify_super_gift_items,param1.item.notify_super_gift_items);
         param1.registerDataCallback(Mod_Item_Base.change_attack_info,param1.item.change_attack_info);
         param1.registerDataCallback(Mod_Item_Base.change_attack_item,param1.item.change_attack_item);
         param1.registerDataCallback(Mod_Item_Base.can_change_list,param1.item.can_change_list);
         param1.registerDataCallback(Mod_Item_Base.can_use_gold_info,param1.item.can_use_gold_info);
         param1.registerDataCallback(Mod_Item_Base.use_gold_oil,param1.item.use_gold_oil);
         param1.registerDataCallback(Mod_Item_Base.get_all_player_item_infos,param1.item.get_all_player_item_infos);
         param1.registerDataCallback(Mod_Item_Base.player_buy_equip_item,param1.item.player_buy_equip_item);
         param1.registerDataCallback(Mod_Item_Base.change_item_info_send_to_client,param1.item.change_item_info_send_to_client);
         param1.registerDataCallback(Mod_Item_Base.open_notify,param1.item.open_notify);
         param1.registerDataCallback(Mod_Item_Base.get_equipment_list,param1.upgrade.get_equipment_list);
         param1.registerDataCallback(Mod_Item_Base.equip_upgrade_stat,param1.upgrade.equip_upgrade_stat);
         param1.registerDataCallback(Mod_Item_Base.clear_upgrade_cd_time,param1.upgrade.clear_upgrade_cd_time);
         param1.registerDataCallback(Mod_Item_Base.open_upgrade_opportunity,param1.upgrade.open_upgrade_opportunity);
         param1.registerDataCallback(Mod_Item_Base.equip_upgrade_stat_list,param1.upgrade.equip_upgrade_stat_list);
         param1.registerDataCallback(Mod_Item_Base.permanent_clean_item_update_cd,param1.upgrade.permanent_clean_item_update_cd);
         param1.registerDataCallback(Mod_Item_Base.get_permanent_clean_item_update_cd,param1.upgrade.get_permanent_clean_item_update_cd);
         param1.registerDataCallback(Mod_Item_Base.get_soul,param1.item.get_soul);
         param1.registerDataCallback(Mod_Item_Base.get_the_item_num,param1.item.get_the_item_num);
         param1.registerDataCallback(Mod_Item_Base.get_gold_oil,param1.item.get_gold_oil);
         param1.registerDataCallback(Mod_Item_Base.take_off_clothes,param1.item.take_off_clothes);
         param1.registerDataCallback(Mod_Item_Base.open_furnace,param1.item.openFurnace);
         param1.registerDataCallback(Mod_Item_Base.drag_furnace_item,param1.item.dragFurnaceItem);
         param1.registerDataCallback(Mod_Item_Base.swap_card,param1.item.swap_card);
         param1.registerDataCallback(Mod_Item_Base.tian_di_yu_pai,param1.item.tian_di_yu_pai);
         param1.registerDataCallback(Mod_Item_Base.get_yupai_info,param1.item.get_yupai_info);
         param1.registerDataCallback(Mod_Item_Base.get_player_gift_all_info,param1.item.get_player_gift_all_info);
         param1.registerDataCallback(Mod_Item_Base.get_gift_deciphe_key,param1.item.get_gift_deciphe_key);
         param1.registerDataCallback(Mod_Item_Base.replace_player_role_equip,param1.item.replace_player_role_equip);
         param1.registerDataCallback(Mod_Item_Base.get_player_role_replace_info,param1.item.get_player_role_replace_info);
         param1.registerDataCallback(Mod_Item_Base.player_role_can_replace_info,param1.item.player_role_can_replace_info);
         param1.registerDataCallback(Mod_Item_Base.large_use_grid_item,param1.item.large_use_grid_item);
         param1.registerDataCallback(Mod_Item_Base.use_set_nickname_item,param1.item.use_set_nickname_item);
         param1.registerDataCallback(Mod_Item_Base.use_set_role_item,param1.item.use_set_role_item);
         param1.registerDataCallback(Mod_Item_Base.player_use_single_item,param1.item.player_use_single_item);
         param1.registerDataCallback(Mod_Item_Base.notify_item_attr_plus,param1.item.notify_item_attr_plus);
         param1.registerDataCallback(Mod_Item_Base.player_use_random_item,param1.item.player_use_random_item);
         param1.registerDataCallback(Mod_Item_Base.get_player_supergift_warehouse_grids,param1.item.get_player_supergift_warehouse_grids);
         param1.registerDataCallback(Mod_Item_Base.move_supergift_warehouse_grid_item_to_pack,param1.item.move_supergift_warehouse_grid_item_to_pack);
         param1.registerDataCallback(Mod_Item_Base.move_pack_grid_item_to_supergift_warehouse,param1.item.move_pack_grid_item_to_supergift_warehouse);
         param1.registerDataCallback(Mod_Item_Base.classify_supergift_warehouse,param1.item.classify_supergift_warehouse);
         param1.registerDataCallback(Mod_Item_Base.change_supergift_warehouse_item_grid,param1.item.change_supergift_warehouse_item_grid);
         param1.registerDataCallback(Mod_Item_Base.use_ding_ji_ji_neng_shu_zi_xuan_bao,param1.item.use_ding_ji_ji_neng_shu_zi_xuan_bao);
         param1.registerDataCallback(Mod_Item_Base.expand_page_two_grid,param1.item.expand_page_two_grid);
         param1.registerDataCallback(Mod_Item_Base.player_use_grid_item_need_choose,param1.item.player_use_grid_item_need_choose);
         param1.registerDataCallback(Mod_Item_Base.use_choose_box,param1.item.use_choose_box);
         param1.registerDataCallback(Mod_Item_Base.player_refresh_grid_item_need_choose,param1.item.player_refresh_grid_item_need_choose);
         param1.registerDataCallback(Mod_Item_Base.get_yun_niang_items,param1.item.get_yun_niang_items);
         param1.registerDataCallback(Mod_Item_Base.buy_yun_niang_item,param1.item.buy_yun_niang_item);
         param1.registerDataCallback(Mod_Item_Base.get_player_friendship_warehouse_grids,param1.item.get_player_friendship_warehouse_grids);
         param1.registerDataCallback(Mod_Item_Base.move_friendship_warehouse_grid_item_to_pack,param1.item.move_friendship_warehouse_grid_item_to_pack);
         param1.registerDataCallback(Mod_Item_Base.move_pack_grid_item_to_friendship_warehouse,param1.item.move_pack_grid_item_to_friendship_warehouse);
         param1.registerDataCallback(Mod_Item_Base.classify_friendship_warehouse,param1.item.classify_friendship_warehouse);
         param1.registerDataCallback(Mod_Item_Base.change_friendship_warehouse_item_grid,param1.item.change_friendship_warehouse_item_grid);
         param1.registerDataCallback(Mod_Item_Base.drop_friendship_warehouse_grid_item,param1.item.drop_friendship_warehouse_grid_item);
         param1.registerDataCallback(Mod_Item_Base.player_batch_grid_item,param1.item.player_batch_grid_item);
         param1.registerDataCallback(Mod_Item_Base.elixir_transform_panel,param1.item.elixir_transform_panel);
         param1.registerDataCallback(Mod_Item_Base.elixir_transform,param1.item.elixir_transform);
      }
   }
}
