package com.protocols
{
   import com.Data;
   
   public class Mod_Notify
   {
       
      
      public function Mod_Notify()
      {
         super();
      }
      
      public static function register(param1:Data) : void
      {
         param1.registerDataCallback(Mod_Notify_Base.mission_award,param1.notify.mission_award);
         param1.registerDataCallback(Mod_Notify_Base.pk_award,param1.notify.pk_award);
         param1.registerDataCallback(Mod_Notify_Base.complete_reel_production,param1.notify.complete_reel_production);
         param1.registerDataCallback(Mod_Notify_Base.disband_faction_notify,param1.notify.disband_faction_notify);
         param1.registerDataCallback(Mod_Notify_Base.kickout_member_notify,param1.notify.kickout_member_notify);
         param1.registerDataCallback(Mod_Notify_Base.role_num_notify,param1.notify.role_num_notify);
         param1.registerDataCallback(Mod_Notify_Base.new_research_notify,param1.notify.new_research_notify);
         param1.registerDataCallback(Mod_Notify_Base.new_partners_notify,param1.notify.new_partners_notify);
         param1.registerDataCallback(Mod_Notify_Base.update_player_super_gift,param1.notify.update_player_super_gift);
         param1.registerDataCallback(Mod_Notify_Base.notify_get_good_fate,param1.notify.notify_get_good_fate);
         param1.registerDataCallback(Mod_Notify_Base.change_equip,param1.notify.change_equip);
         param1.registerDataCallback(Mod_Notify_Base.update_lucky_shop_item,param1.notify.update_lucky_shop_item);
         param1.registerDataCallback(Mod_Notify_Base.buy_good_stuff_in_lucky_shop,param1.notify.buy_good_stuff_in_lucky_shop);
         param1.registerDataCallback(Mod_Notify_Base.notify_player_mission_practice_status,param1.notify.notify_player_mission_practice_status);
         param1.registerDataCallback(Mod_Notify_Base.player_take_bible,param1.notify.player_take_bible);
         param1.registerDataCallback(Mod_Notify_Base.player_take_bible_berobbed,param1.notify.player_take_bible_berobbed);
         param1.registerDataCallback(Mod_Notify_Base.game_timer,param1.notify.game_timer);
         param1.registerDataCallback(Mod_Notify_Base.send_flower,param1.notify.send_flower);
         param1.registerDataCallback(Mod_Notify_Base.pass_tower,param1.notify.pass_tower);
         param1.registerDataCallback(Mod_Notify_Base.update_rulai_status,param1.notify.update_rulai_status);
         param1.registerDataCallback(Mod_Notify_Base.roll_cake,param1.notify.roll_cake);
         param1.registerDataCallback(Mod_Notify_Base.update_server_war_step,param1.notify.update_server_war_step);
         param1.registerDataCallback(Mod_Notify_Base.have_new_server_war_report,param1.notify.have_new_server_war_report);
         param1.registerDataCallback(Mod_Notify_Base.server_war_winner,param1.notify.server_war_winner);
         param1.registerDataCallback(Mod_Notify_Base.update_twin_dragons_step,param1.notify.update_twin_dragons_step);
         param1.registerDataCallback(Mod_Notify_Base.have_new_twin_dragons_report,param1.notify.have_new_twin_dragons_report);
         param1.registerDataCallback(Mod_Notify_Base.twin_dragons_winner,param1.notify.twin_dragons_winner);
         param1.registerDataCallback(Mod_Notify_Base.server_faction_war_winner,param1.notify.server_faction_war_winner);
         param1.registerDataCallback(Mod_Notify_Base.world_war_top_login,param1.notify.world_war_top_login);
         param1.registerDataCallback(Mod_Notify_Base.zodiac_entry_notify,param1.notify.zodiac_entry_notify);
         param1.registerDataCallback(Mod_Notify_Base.get_pet_animal_exp,param1.notify.get_pet_animal_exp);
         param1.registerDataCallback(Mod_Notify_Base.study_stunt_notify,param1.notify.study_stunt_notify);
         param1.registerDataCallback(Mod_Notify_Base.flower_week_number_one,param1.notify.flower_week_number_one);
         param1.registerDataCallback(Mod_Notify_Base.cat_hunt_golden_box,param1.notify.cat_hunt_golden_box);
         param1.registerDataCallback(Mod_Notify_Base.update_world_faction_war_step,param1.notify.update_world_faction_war_step);
         param1.registerDataCallback(Mod_Notify_Base.update_world_faction_war_team,param1.notify.update_world_faction_war_team);
         param1.registerDataCallback(Mod_Notify_Base.world_faction_war_winner,param1.notify.world_faction_war_winner);
         param1.registerDataCallback(Mod_Notify_Base.have_new_world_faction_war_report,param1.notify.have_new_world_faction_war_report);
         param1.registerDataCallback(Mod_Notify_Base.week_ranking,param1.notify.week_ranking);
         param1.registerDataCallback(Mod_Notify_Base.special_notify,param1.notify.special_notify);
         param1.registerDataCallback(Mod_Notify_Base.find_immortal_five_notify,param1.notify.find_immortal_five_notify);
         param1.registerDataCallback(Mod_Notify_Base.five_blessings_notify,param1.notify.five_blessings_notify);
         param1.registerDataCallback(Mod_Notify_Base.unlock_special_partner,param1.notify.unlock_special_partner);
         param1.registerDataCallback(Mod_Notify_Base.world_top_war_gift_has_white_tiger,param1.notify.world_top_war_gift_has_white_tiger);
         param1.registerDataCallback(Mod_Notify_Base.lucky_wheel_award_seven_medicine_reel,param1.notify.lucky_wheel_award_seven_medicine_reel);
         param1.registerDataCallback(Mod_Notify_Base.update_server_faction_war_step,param1.notify.update_server_faction_war_step);
         param1.registerDataCallback(Mod_Notify_Base.have_new_server_faction_war_report,param1.notify.have_new_server_faction_war_report);
         param1.registerDataCallback(Mod_Notify_Base.ingot_luck_wheel_notify,param1.notify.ingot_luck_wheel_notify);
         param1.registerDataCallback(Mod_Notify_Base.study_sigil_stunt_notify,param1.notify.study_sigil_stunt_notify);
         param1.registerDataCallback(Mod_Notify_Base.get_good_fate_notify,param1.notify.get_good_fate_notify);
         param1.registerDataCallback(Mod_Notify_Base.notify_unlock_excl_arti,param1.notify.notify_unlock_excl_arti);
         param1.registerDataCallback(Mod_Notify_Base.notify_christmas_activity_award,param1.notify.notify_christmas_activity_award);
         param1.registerDataCallback(Mod_Notify_Base.notify_player_change_job,param1.notify.notify_player_change_job);
         param1.registerDataCallback(Mod_Notify_Base.notify_lantern_festival_award,param1.notify.notify_lantern_festival_award);
         param1.registerDataCallback(Mod_Notify_Base.open_st_boss_gift_notify,param1.notify.open_st_boss_gift_notify);
         param1.registerDataCallback(Mod_Notify_Base.notify_unlock_supernatural,param1.notify.notify_unlock_supernatural);
         param1.registerDataCallback(Mod_Notify_Base.study_exclusive_supernatural_notify,param1.notify.study_exclusive_supernatural_notify);
         param1.registerDataCallback(Mod_Notify_Base.notify_player_hunt_demon_award,param1.notify.notify_player_hunt_demon_award);
         param1.registerDataCallback(Mod_Notify_Base.have_new_new_top_war_report,param1.notify.have_new_new_top_war_report);
         param1.registerDataCallback(Mod_Notify_Base.new_top_war_winner,param1.notify.new_top_war_winner);
         param1.registerDataCallback(Mod_Notify_Base.circle_war_notify,param1.notify.circle_war_notify);
         param1.registerDataCallback(Mod_Notify_Base.sacrifice_dragonball_notify,param1.notify.sacrifice_dragonball_notify);
         param1.registerDataCallback(Mod_Notify_Base.sacrifice_dragonball_world_channel_notify,param1.notify.sacrifice_dragonball_world_channel_notify);
         param1.registerDataCallback(Mod_Notify_Base.gamable_level_1_notify,param1.notify.gamable_level_1_notify);
         param1.registerDataCallback(Mod_Notify_Base.gamable_result_notify,param1.notify.gamable_result_notify);
         param1.registerDataCallback(Mod_Notify_Base.player_st_take_bible,param1.notify.player_st_take_bible);
         param1.registerDataCallback(Mod_Notify_Base.player_st_take_bible_berobbed,param1.notify.player_st_take_bible_berobbed);
         param1.registerDataCallback(Mod_Notify_Base.update_st_sup_war_step,param1.notify.update_st_sup_war_step);
         param1.registerDataCallback(Mod_Notify_Base.have_new_st_sup_war_report,param1.notify.have_new_st_sup_war_report);
         param1.registerDataCallback(Mod_Notify_Base.st_sup_war_winner,param1.notify.st_sup_war_winner);
         param1.registerDataCallback(Mod_Notify_Base.notify_luxury_seat,param1.notify.notify_luxury_seat);
         param1.registerDataCallback(Mod_Notify_Base.have_new_god_war_report,param1.notify.have_new_god_war_report);
         param1.registerDataCallback(Mod_Notify_Base.god_war_winner,param1.notify.god_war_winner);
         param1.registerDataCallback(Mod_Notify_Base.sky_lantern_bless_gold_quality,param1.notify.sky_lantern_bless_gold_quality);
         param1.registerDataCallback(Mod_Notify_Base.world_sky_lantern_bless_gold_quality,param1.notify.world_sky_lantern_bless_gold_quality);
         param1.registerDataCallback(Mod_Notify_Base.war_power_change,param1.notify.war_power_change);
         param1.registerDataCallback(Mod_Notify_Base.sky_lantern_bless_top_one,param1.notify.sky_lantern_bless_top_one);
         param1.registerDataCallback(Mod_Notify_Base.make_chaos_item,param1.notify.make_chaos_item);
         param1.registerDataCallback(Mod_Notify_Base.notify_travel_shop_status,param1.notify.notify_travel_shop_status);
         param1.registerDataCallback(Mod_Notify_Base.notify_player_new_gift,param1.notify.notify_player_new_gift);
         param1.registerDataCallback(Mod_Notify_Base.christmas_hunt_demon_notify,param1.notify.christmas_hunt_demon_notify);
         param1.registerDataCallback(Mod_Notify_Base.become_immortal,param1.notify.become_immortal);
         param1.registerDataCallback(Mod_Notify_Base.notify_st_boss_detect_title,param1.notify.notify_st_boss_detect_title);
         param1.registerDataCallback(Mod_Notify_Base.lotus_lamp_colorful_quality,param1.notify.lotus_lamp_colorful_quality);
         param1.registerDataCallback(Mod_Notify_Base.wish_tree_good_quality,param1.notify.wish_tree_good_quality);
         param1.registerDataCallback(Mod_Notify_Base.notify_card_master_draw,param1.notify.notify_card_master_draw);
         param1.registerDataCallback(Mod_Notify_Base.super_prize_pool_notify,param1.notify.super_prize_pool_notify);
         param1.registerDataCallback(Mod_Notify_Base.awake_skill_book_notify,param1.notify.awake_skill_book_notify);
         param1.registerDataCallback(Mod_Notify_Base.firework_notify,param1.notify.firework_notify);
         param1.registerDataCallback(Mod_Notify_Base.marry_notify,param1.notify.marry_notify);
         param1.registerDataCallback(Mod_Notify_Base.change_notify,param1.notify.change_notify);
         param1.registerDataCallback(Mod_Notify_Base.lottery_ticket_winner_notify,param1.notify.lottery_ticket_winner_notify);
         param1.registerDataCallback(Mod_Notify_Base.four_anniversary_back_lottery_notify,param1.notify.four_anniversary_back_lottery_notify);
         param1.registerDataCallback(Mod_Notify_Base.st_indiana_jones_box_award,param1.notify.st_indiana_jones_box_award);
         param1.registerDataCallback(Mod_Notify_Base.update_st_arena_step,param1.notify.update_st_arena_step);
         param1.registerDataCallback(Mod_Notify_Base.have_new_st_union_sixvsix_report,param1.notify.have_new_st_union_sixvsix_report);
         param1.registerDataCallback(Mod_Notify_Base.update_st_union_sixvsix_step,param1.notify.update_st_union_sixvsix_step);
         param1.registerDataCallback(Mod_Notify_Base.st_union_sixvsix_winner,param1.notify.st_union_sixvsix_winner);
         param1.registerDataCallback(Mod_Notify_Base.hide_treasure_map_item,param1.notify.hide_treasure_map_item);
         param1.registerDataCallback(Mod_Notify_Base.notify_sa_luxury_seat,param1.notify.notify_sa_luxury_seat);
         param1.registerDataCallback(Mod_Notify_Base.notify_activity_award,param1.notify.notify_activity_award);
         param1.registerDataCallback(Mod_Notify_Base.update_new_server_war_step,param1.notify.update_new_server_war_step);
         param1.registerDataCallback(Mod_Notify_Base.new_have_new_server_war_report,param1.notify.new_have_new_server_war_report);
         param1.registerDataCallback(Mod_Notify_Base.zongzi_vote_camp_vote,param1.notify.zongzi_vote_camp_vote);
      }
   }
}
